/**
 * This code was generated by Builder.io
 */
import React from "react";

function TableRow({
  RFQnumber,
  customername,
  place,
  RFQdate,
  TypeOfgoods,
  RFQmedia,
  Lastdateofsubmission,
  Requestrefnumber,
  contactpersonname,
  contactemail,
  contactnumber,
  status,
  action
}) {
  return (
    <div className="flex flex-wrap gap-4 justify-center items-center p-4 w-full bg-white border-b-2 border-blue-100 max-md:max-w-full">
      <div className="flex-1 shrink my-auto text-sm font-medium text-center whitespace-nowrap text-sky-950">
        {RFQnumber}
      </div>
      <div className="flex-1 shrink my-auto text-sm font-medium text-sky-950">
        {customername}
      </div>
      <div className="flex-1 shrink my-auto text-sm font-medium text-sky-950">
        {place}
      </div>
      <div className="flex-1 shrink my-auto text-sm font-medium text-sky-950">
        {RFQdate}
      </div>
      <div className="flex-1 shrink my-auto text-sm font-medium text-sky-950">
        {TypeOfgoods}
      </div>
      <div className="flex-1 shrink my-auto text-sm font-medium text-sky-950">
        {RFQmedia}
      </div>
      <div className="flex-1 shrink my-auto text-sm font-medium text-sky-950">
        {Lastdateofsubmission}
      </div>
      <div className="flex-1 shrink my-auto text-sm font-medium text-sky-950">
        {Requestrefnumber}
      </div>
      <div className="flex-1 shrink my-auto text-sm font-medium text-sky-950">
        {contactpersonname}
      </div>
      <div className="flex-1 shrink my-auto text-sm font-medium text-sky-950">
        {contactemail}
      </div>
      <div className="flex-1 shrink my-auto text-sm font-medium text-sky-950">
        {contactnumber}
      </div>
      <div className="flex flex-1 shrink items-center my-auto text-xs font-medium text-green-600 whitespace-nowrap basis-0">
        <div className="px-3 py-2 bg-emerald-50 rounded-3xl">
          {status}
        </div>
      </div>
      <div className="flex flex-1 shrink justify-center items-center basis-0">
        <div className="flex gap-4 items-center">
          {action}
        </div>
      </div>
    </div>
  );
}

export default TableRow;
