/**
 * This code was generated by Builder.io
 */
import React from "react";
// import Sidebar from "../Components/Sidebar";
import ViewAllRFQTable from "./ViewAllRFQTable";

function ViewAllRFQPage() {
  return (
    <div className="flex flex-col p-4 min-h-screen bg-white">
      <ViewAllRFQTable />
    </div>
  );
}

export default ViewAllRFQPage;
