import React from "react";

function TableHeader() {
  return (
    <div className="flex flex-wrap gap-4 justify-center items-center p-4 w-full text-sm font-bold bg-blue-100 text-sky-950 max-md:max-w-full">
      <div className="flex-1 shrink gap-1 self-stretch my-auto text-center">
        Work Order <br /> Number
      </div>
      <div className="flex-1 shrink gap-1 self-stretch my-auto">PO Number</div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto whitespace-nowrap">
        Customer
      </div>
      <div className="flex flex-1 shrink gap-2 items-center self-stretch my-auto basis-0">
        <div className="flex-1 shrink self-stretch my-auto basis-0">
          Po Date
        </div>
        <div className="flex shrink-0 self-stretch my-auto w-4 h-4" />
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto whitespace-nowrap">
        Amount
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto">
        Project Engineer
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto">
        Quality Engineer
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto">
        Delivery Date
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto whitespace-nowrap">
        Status
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto whitespace-nowrap">
        Remarks
      </div>
      <div className="flex-1 shrink self-stretch my-auto basis-0">Action</div>
    </div>
  );
}

export default TableHeader;


// /**
//  * This code was generated by Builder.io
//  */
// import React from "react";
// import HEADER_ITEMS from "../../constants/tableHeader";

// function TableHeader() {
//   const headerList = ["Work Order Number", "PO Number", "Delivery Date", "Remarks", "Action"];

//   return (
//     <div className="flex w-full bg-blue-100 text-sky-950 font-bold text-sm p-4 max-md:max-w-full">
//       {headerList.map((item, index) => (
//         <div
//           key={index}
//           className="flex-1 min-w-0 text-center whitespace-nowrap"
//         >
//           {item}
//         </div>
//       ))}
//     </div>
//   );
// }

// export default TableHeader;


