/**
 * This code was generated by Builder.io
 */
import React from "react";

function TableHeader() {
  return (
    <div className="flex flex-wrap gap-4 justify-center items-center p-4 w-full text-sm font-bold bg-blue-100 text-sky-950 max-md:max-w-full">
      <div className="flex-1 shrink gap-1 self-stretch my-auto text-center">
        SI No
      </div>
      <div className="flex-1 shrink gap-1 self-stretch my-auto text-center">
        Quotation No
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-center">
        Customer Name
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-center">
        Place
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-center">
        Value
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-center">
        Contact Person
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-center">
        Date
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-center">
        View
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-center">
        Approval
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-center">
        Reason
      </div>
    </div>
  );
}

export default TableHeader;
