/**
 * This code was generated by Builder.io
 */
import React from "react";

function TableRow({
  id,
  item,
  customer,
  poDate,
  amount,
  projectEngineer,
  qualityEngineer,
  deliveryDate,
  status,
  remarks,
}) {
  return (
    <div className="flex flex-wrap gap-4 justify-center items-center p-4 w-full bg-white border-b-2 border-blue-100 max-md:max-w-full">
      <div className="flex-1 shrink gap-1 self-stretch my-auto text-sm font-medium text-center whitespace-nowrap text-sky-950">
        {id}
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-sm font-medium whitespace-nowrap text-sky-950">
        {item}
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-sm font-medium text-sky-950">
        {customer}
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-sm font-medium whitespace-nowrap text-sky-950">
        {poDate}
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-sm font-medium text-sky-950">
        {amount}
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-sm font-medium text-sky-950">
        {projectEngineer}
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-sm font-medium text-sky-950">
        {qualityEngineer}
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-sm font-medium whitespace-nowrap text-sky-950">
        {deliveryDate}
      </div>
      <div className="flex flex-1 shrink gap-2 items-center self-stretch my-auto text-xs font-medium text-green-600 whitespace-nowrap basis-0">
        <div className="gap-2.5 self-stretch px-3 py-2 my-auto bg-emerald-50 rounded-3xl">
          {status}
        </div>
      </div>
      <div className="flex-1 shrink gap-2 self-stretch my-auto text-sm font-medium text-sky-950">
        {remarks}
      </div>
      <div className="flex flex-1 shrink gap-2 justify-center items-center self-stretch my-auto basis-0">
        <div className="flex gap-4 items-center self-stretch my-auto w-6">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/b927a60f8772abac0087201a4aca97ce8701ca514440f12a349586774018b389?placeholderIfAbsent=true&apiKey=59c3577b3bf2468eadc2026e9528e39d"
            className="object-contain self-stretch my-auto w-6 aspect-square"
            alt=""
          />
        </div>
      </div>
    </div>
  );
}

export default TableRow;
