/**
 * This code was generated by Builder.io
 */
import React from "react";
import TableHeader from "./TableHeader";
import TableRow from "./TableRow";
import FilterSection from "../components/FilterSection";

const tableData = [
  {
    id: "#20462",
    item: "Hat",
    customer: "Matt Dickerson",
    poDate: "13/05/2022",
    amount: "$4.95",
    projectEngineer: "Transfer Bank",
    deliveryDate: "13/05/2022",
    status: "Delivered",
    remarks: "Transfer Bank",
    customerAcceptanceStatus: Math.random() > 0.5 ? "Accepted" : "Rejected", // Randomized values
  },
  {
    id: "#20462",
    item: "Hat",
    customer: "Matt Dickerson",
    poDate: "13/05/2022",
    amount: "$4.95",
    projectEngineer: "Transfer Bank",
    deliveryDate: "13/05/2022",
    status: "Delivered",
    remarks: "Transfer Bank",
    customerAcceptanceStatus: Math.random() > 0.5 ? "Accepted" : "Rejected",
  },
  {
    id: "#20462",
    item: "Hat",
    customer: "Matt Dickerson",
    poDate: "13/05/2022",
    amount: "$4.95",
    projectEngineer: "Transfer Bank",
    deliveryDate: "13/05/2022",
    status: "Delivered",
    remarks: "Transfer Bank",
    customerAcceptanceStatus: Math.random() > 0.5 ? "Accepted" : "Rejected",
  },
  {
    id: "#20462",
    item: "Hat",
    customer: "Matt Dickerson",
    poDate: "13/05/2022",
    amount: "$4.95",
    projectEngineer: "Transfer Bank",
    deliveryDate: "13/05/2022",
    status: "Delivered",
    remarks: "Transfer Bank",
    customerAcceptanceStatus: Math.random() > 0.5 ? "Accepted" : "Rejected",
  },
  {
    id: "#20462",
    item: "Hat",
    customer: "Matt Dickerson",
    poDate: "13/05/2022",
    amount: "$4.95",
    projectEngineer: "Transfer Bank",
    deliveryDate: "13/05/2022",
    status: "Delivered",
    remarks: "Transfer Bank",
    customerAcceptanceStatus: Math.random() > 0.5 ? "Accepted" : "Rejected",
  },
  {
    id: "#20462",
    item: "Hat",
    customer: "Matt Dickerson",
    poDate: "13/05/2022",
    amount: "$4.95",
    projectEngineer: "Transfer Bank",
    deliveryDate: "13/05/2022",
    status: "Delivered",
    remarks: "Transfer Bank",
    customerAcceptanceStatus: Math.random() > 0.5 ? "Accepted" : "Rejected",
  },
  {
    id: "#20462",
    item: "Hat",
    customer: "Matt Dickerson",
    poDate: "13/05/2022",
    amount: "$4.95",
    projectEngineer: "Transfer Bank",
    deliveryDate: "13/05/2022",
    status: "Delivered",
    remarks: "Transfer Bank",
    customerAcceptanceStatus: Math.random() > 0.5 ? "Accepted" : "Rejected",
  },
  {
    id: "#20462",
    item: "Hat",
    customer: "Matt Dickerson",
    poDate: "13/05/2022",
    amount: "$4.95",
    projectEngineer: "Transfer Bank",
    deliveryDate: "13/05/2022",
    status: "Delivered",
    remarks: "Transfer Bank",
    customerAcceptanceStatus: Math.random() > 0.5 ? "Accepted" : "Rejected",
  },
  {
    id: "#20462",
    item: "Hat",
    customer: "Matt Dickerson",
    poDate: "13/05/2022",
    amount: "$4.95",
    projectEngineer: "Transfer Bank",
    deliveryDate: "13/05/2022",
    status: "Delivered",
    remarks: "Transfer Bank",
    customerAcceptanceStatus: Math.random() > 0.5 ? "Accepted" : "Rejected",
  },
  {
    id: "#20462",
    item: "Hat",
    customer: "Matt Dickerson",
    poDate: "13/05/2022",
    amount: "$4.95",
    projectEngineer: "Transfer Bank",
    deliveryDate: "13/05/2022",
    status: "Delivered",
    remarks: "Transfer Bank",
    customerAcceptanceStatus: Math.random() > 0.5 ? "Accepted" : "Rejected",
  },
];


function ProjectStatusTable() {
  return (
    <div className="flex flex-col  w-full max-md:max-w-full">
      <div classname="pb-[24px] ">
        <FilterSection className="my-[24px] mb-[24px]" />
        <TableHeader className="mt-[24px]" />
        {tableData.map((row, index) => (
          <TableRow key={index} {...row} />
        ))}
      </div>
    </div>
  );
}

export default ProjectStatusTable;
