/**
 * This code was generated by Builder.io
 */
import React from "react";
import TableHeader from "./TableHeader";
import TableRow from "./TableRow";
import FilterSection from "../../components/FilterSection";

const tableData = [
  {
    RFQnumber: "#20462",
    customername: "Matt Dickerson",
    place: "New York",
    RFQdate: "13/05/2022",
    TypeOfgoods: "Hat",
    RFQmedia: "Email",
    Lastdateofsubmission: "15/05/2022",
    Requestrefnumber: "REQ12345",
    contactpersonname: "John Doe",
    contactemail: "john.doe@example.com",
    contactnumber: "+1-123-456-7890",
    status: "Delivered",
    action: "View Details",
  },
  {
    RFQnumber: "#20463",
    customername: "Sarah Lee",
    place: "California",
    RFQdate: "14/05/2022",
    TypeOfgoods: "Shirt",
    RFQmedia: "Phone",
    Lastdateofsubmission: "16/05/2022",
    Requestrefnumber: "REQ12346",
    contactpersonname: "Jane Smith",
    contactemail: "jane.smith@example.com",
    contactnumber: "+1-123-456-7891",
    status: "Pending",
    action: "View Details",
  },
  {
    RFQnumber: "#20464",
    customername: "Mike Johnson",
    place: "Texas",
    RFQdate: "15/05/2022",
    TypeOfgoods: "Shoes",
    RFQmedia: "Online Portal",
    Lastdateofsubmission: "17/05/2022",
    Requestrefnumber: "REQ12347",
    contactpersonname: "Robert Brown",
    contactemail: "robert.brown@example.com",
    contactnumber: "+1-123-456-7892",
    status: "Delivered",
    action: "View Details",
  },
  {
    RFQnumber: "#20465",
    customername: "Emily Davis",
    place: "Florida",
    RFQdate: "16/05/2022",
    TypeOfgoods: "Jacket",
    RFQmedia: "Email",
    Lastdateofsubmission: "18/05/2022",
    Requestrefnumber: "REQ12348",
    contactpersonname: "Emma Wilson",
    contactemail: "emma.wilson@example.com",
    contactnumber: "+1-123-456-7893",
    status: "Pending",
    action: "View Details",
  },
  {
    RFQnumber: "#20466",
    customername: "Chris Brown",
    place: "Nevada",
    RFQdate: "17/05/2022",
    TypeOfgoods: "Gloves",
    RFQmedia: "Phone",
    Lastdateofsubmission: "19/05/2022",
    Requestrefnumber: "REQ12349",
    contactpersonname: "Olivia Martin",
    contactemail: "olivia.martin@example.com",
    contactnumber: "+1-123-456-7894",
    status: "Delivered",
    action: "View Details",
  },
  {
    RFQnumber: "#20467",
    customername: "Sophia Taylor",
    place: "Arizona",
    RFQdate: "18/05/2022",
    TypeOfgoods: "Pants",
    RFQmedia: "Online Portal",
    Lastdateofsubmission: "20/05/2022",
    Requestrefnumber: "REQ12350",
    contactpersonname: "Liam Moore",
    contactemail: "liam.moore@example.com",
    contactnumber: "+1-123-456-7895",
    status: "Pending",
    action: "View Details",
  },
  {
    RFQnumber: "#20468",
    customername: "Daniel White",
    place: "Ohio",
    RFQdate: "19/05/2022",
    TypeOfgoods: "Socks",
    RFQmedia: "Email",
    Lastdateofsubmission: "21/05/2022",
    Requestrefnumber: "REQ12351",
    contactpersonname: "Noah Anderson",
    contactemail: "noah.anderson@example.com",
    contactnumber: "+1-123-456-7896",
    status: "Delivered",
    action: "View Details",
  },
  {
    RFQnumber: "#20469",
    customername: "Mia Clark",
    place: "Michigan",
    RFQdate: "20/05/2022",
    TypeOfgoods: "Tie",
    RFQmedia: "Phone",
    Lastdateofsubmission: "22/05/2022",
    Requestrefnumber: "REQ12352",
    contactpersonname: "Ethan Hall",
    contactemail: "ethan.hall@example.com",
    contactnumber: "+1-123-456-7897",
    status: "Pending",
    action: "View Details",
  },
  {
    RFQnumber: "#20470",
    customername: "Ava Scott",
    place: "Georgia",
    RFQdate: "21/05/2022",
    TypeOfgoods: "Coat",
    RFQmedia: "Online Portal",
    Lastdateofsubmission: "23/05/2022",
    Requestrefnumber: "REQ12353",
    contactpersonname: "Mason Turner",
    contactemail: "mason.turner@example.com",
    contactnumber: "+1-123-456-7898",
    status: "Delivered",
    action: "View Details",
  },
  {
    RFQnumber: "#20471",
    customername: "Isabella King",
    place: "Colorado",
    RFQdate: "22/05/2022",
    TypeOfgoods: "Belt",
    RFQmedia: "Email",
    Lastdateofsubmission: "24/05/2022",
    Requestrefnumber: "REQ12354",
    contactpersonname: "James Adams",
    contactemail: "james.adams@example.com",
    contactnumber: "+1-123-456-7899",
    status: "Pending",
    action: "View Details",
  },
];


function PendingRFQTable() {
  return (
    <div className="flex flex-col w-full max-md:max-w-full overflow-auto ">
      <FilterSection /> {/* Applying 24px top and bottom margin */}
      <TableHeader />
      {tableData.map((row, index) => (
        <TableRow key={index} {...row} />
      ))}
    </div>
  );
}

export default PendingRFQTable;
